# Generated by Django 5.2.13 on 2026-06-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_exfilresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostresult',
            options={'ordering': ['ip_address']},
        ),
        migrations.AlterModelOptions(
            name='portfinding',
            options={'ordering': ['port']},
        ),
        migrations.AlterModelOptions(
            name='scanrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='agent',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scanrequest',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_requests', to='scanner.agent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='exfilresult',
            name='profile',
            field=models.CharField(choices=[('burst', 'Burst'), ('slow_drip', 'Slow Drip'), ('jitter', 'Jitter')], default='burst', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanrequest',
            name='cached_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.scanrequest'),
        ),
        migrations.AlterField(
            model_name='scanrequest',
            name='scan_profile',
            field=models.CharField(choices=[('fast', 'Fast (top 100 ports)'), ('default', 'Default (top 1000 ports)'), ('deep', 'Deep (all ports + OS)'), ('ping', 'Ping sweep')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanrequest',
            name='target',
            field=models.CharField(max_length=255),
        ),
    ]
